name: go vet test

on:
  pull_request:
  push:

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.10
        with:
          repository: Yandex-Practicum/go-autotests
          latest: false
          tag: "v0.10.11"
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
